"""Seed the Neo4j knowledge graph with realistic industrial data for demo purposes.
Reads from the JSON files generated by generate_realistic_data.py.
"""

import asyncio
import sys
import os
import json

# Add parent dir to path so we can import from backend
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'backend')))


async def seed_knowledge_graph():
    """Pre-populate the knowledge graph with sample industrial data."""
    from database.neo4j_client import Neo4jClient

    print("🌱 Seeding Knowledge Graph with Realistic Data...")
    await Neo4jClient.connect()

    # Clear existing graph
    print("  Clearing existing graph...")
    await Neo4jClient.execute_write("MATCH (n) DETACH DELETE n")

    data_dir = os.path.join(os.path.dirname(__file__), 'generated')

    # Helper function to load json
    def load_json(filename):
        filepath = os.path.join(data_dir, filename)
        if not os.path.exists(filepath):
            print(f"  ⚠️ Warning: {filename} not found. Run generate_realistic_data.py first.")
            return []
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)

    # ================================================================
    # 1. Load Nodes
    # ================================================================
    
    # Equipment
    equipment = load_json("equipment.json")
    for eq in equipment:
        await Neo4jClient.execute_write(
            "MERGE (e:Equipment {tag: $tag}) SET e += $props",
            {"tag": eq["tag"], "props": eq},
        )
    print(f"  ✓ Created {len(equipment)} equipment nodes")

    # Regulations
    regulations = load_json("regulations.json")
    for reg in regulations:
        await Neo4jClient.execute_write(
            "MERGE (r:Regulation {standard_id: $sid}) SET r += $props",
            {"sid": reg["standard_id"], "props": reg},
        )
    print(f"  ✓ Created {len(regulations)} regulation nodes")

    # Personnel
    personnel = load_json("personnel.json")
    for p in personnel:
        await Neo4jClient.execute_write(
            "MERGE (p:Personnel {employee_id: $eid}) SET p += $props",
            {"eid": p["employee_id"], "props": p},
        )
    print(f"  ✓ Created {len(personnel)} personnel nodes")

    # Failure Modes
    failure_modes = load_json("failure_modes.json")
    for fm in failure_modes:
        await Neo4jClient.execute_write(
            "MERGE (fm:FailureMode {code: $code}) SET fm += $props",
            {"code": fm["code"], "props": fm},
        )
    print(f"  ✓ Created {len(failure_modes)} failure mode nodes")

    # Procedures
    procedures = load_json("procedures.json")
    for proc in procedures:
        await Neo4jClient.execute_write(
            "MERGE (p:Procedure {procedure_id: $pid}) SET p += $props",
            {"pid": proc["procedure_id"], "props": proc},
        )
    print(f"  ✓ Created {len(procedures)} procedure nodes")

    # Process Parameters
    process_params = load_json("process_parameters.json")
    for pp in process_params:
        await Neo4jClient.execute_write(
            "MERGE (pp:ProcessParameter {name: $name}) SET pp += $props",
            {"name": pp["name"], "props": pp},
        )
    print(f"  ✓ Created {len(process_params)} process parameter nodes")

    # Maintenance Records
    maintenance_records = load_json("maintenance_records.json")
    for mr in maintenance_records:
        await Neo4jClient.execute_write(
            "MERGE (m:MaintenanceRecord {work_order_id: $woid}) SET m += $props",
            {"woid": mr["work_order_id"], "props": mr},
        )
    print(f"  ✓ Created {len(maintenance_records)} maintenance record nodes")

    # Inspection Findings
    inspection_findings = load_json("inspection_findings.json")
    for inf in inspection_findings:
        await Neo4jClient.execute_write(
            "MERGE (i:InspectionFinding {finding_id: $fid}) SET i += $props",
            {"fid": inf["finding_id"], "props": inf},
        )
    print(f"  ✓ Created {len(inspection_findings)} inspection finding nodes")

    # ================================================================
    # 2. Load Relationships
    # ================================================================
    print("  Creating relationships...")
    rels = load_json("relationships.json")

    if rels:
        # Equipment -> Failure Modes
        for tag, code in rels.get("equipment_failure_modes", []):
            await Neo4jClient.execute_write(
                "MATCH (e:Equipment {tag: $tag}), (fm:FailureMode {code: $code}) MERGE (e)-[:HAS_FAILURE_MODE]->(fm)",
                {"tag": tag, "code": code},
            )

        # Equipment -> Regulations
        for tag, sid in rels.get("equipment_regulations", []):
            await Neo4jClient.execute_write(
                "MATCH (e:Equipment {tag: $tag}), (r:Regulation {standard_id: $sid}) MERGE (e)-[:GOVERNED_BY]->(r)",
                {"tag": tag, "sid": sid},
            )

        # Equipment -> Procedures
        for tag, pid in rels.get("equipment_procedures", []):
            await Neo4jClient.execute_write(
                "MATCH (e:Equipment {tag: $tag}), (p:Procedure {procedure_id: $pid}) MERGE (e)-[:FOLLOWS_PROCEDURE]->(p)",
                {"tag": tag, "pid": pid},
            )

        # Procedure -> Regulation (COMPLIES_WITH)
        for pid, sid in rels.get("procedure_regulations", []):
            await Neo4jClient.execute_write(
                "MATCH (p:Procedure {procedure_id: $pid}), (r:Regulation {standard_id: $sid}) MERGE (p)-[:COMPLIES_WITH]->(r)",
                {"pid": pid, "sid": sid},
            )

        # FailureMode -> Procedure (MITIGATED_BY)
        for code, pid in rels.get("failure_mode_procedures", []):
            await Neo4jClient.execute_write(
                "MATCH (fm:FailureMode {code: $code}), (p:Procedure {procedure_id: $pid}) MERGE (fm)-[:MITIGATED_BY]->(p)",
                {"code": code, "pid": pid},
            )

        # Equipment -> MaintenanceRecord (HAS_MAINTENANCE)
        for tag, woid in rels.get("equipment_maintenance", []):
            await Neo4jClient.execute_write(
                "MATCH (e:Equipment {tag: $tag}), (m:MaintenanceRecord {work_order_id: $woid}) MERGE (e)-[:HAS_MAINTENANCE]->(m)",
                {"tag": tag, "woid": woid},
            )

        # MaintenanceRecord -> Personnel (PERFORMED_BY)
        for woid, eid in rels.get("maintenance_personnel", []):
            await Neo4jClient.execute_write(
                "MATCH (m:MaintenanceRecord {work_order_id: $woid}), (p:Personnel {employee_id: $eid}) MERGE (m)-[:PERFORMED_BY]->(p)",
                {"woid": woid, "eid": eid},
            )

        # MaintenanceRecord -> FailureMode (CAUSED_BY)
        for woid, code in rels.get("maintenance_failure_modes", []):
            await Neo4jClient.execute_write(
                "MATCH (m:MaintenanceRecord {work_order_id: $woid}), (fm:FailureMode {code: $code}) MERGE (m)-[:CAUSED_BY]->(fm)",
                {"woid": woid, "code": code},
            )

        # InspectionFinding -> Equipment (IDENTIFIED_ON)
        for fid, tag in rels.get("inspection_equipment", []):
            await Neo4jClient.execute_write(
                "MATCH (i:InspectionFinding {finding_id: $fid}), (e:Equipment {tag: $tag}) MERGE (i)-[:IDENTIFIED_ON]->(e)",
                {"fid": fid, "tag": tag},
            )

        # InspectionFinding -> Personnel (INSPECTED_BY)
        for fid, eid in rels.get("inspection_personnel", []):
            await Neo4jClient.execute_write(
                "MATCH (i:InspectionFinding {finding_id: $fid}), (p:Personnel {employee_id: $eid}) MERGE (i)-[:INSPECTED_BY]->(p)",
                {"fid": fid, "eid": eid},
            )

        # InspectionFinding -> Regulation (VIOLATES / NON_COMPLIANCE_WITH)
        for fid, sid in rels.get("inspection_regulations", []):
            await Neo4jClient.execute_write(
                "MATCH (i:InspectionFinding {finding_id: $fid}), (r:Regulation {standard_id: $sid}) MERGE (i)-[:REFERENCES]->(r)",
                {"fid": fid, "sid": sid},
            )
            
        # Equipment -> ProcessParameter (MONITORED_BY)
        for tag, pname in rels.get("equipment_process_params", []):
            await Neo4jClient.execute_write(
                "MATCH (e:Equipment {tag: $tag}), (pp:ProcessParameter {name: $pname}) MERGE (e)-[:MONITORED_BY]->(pp)",
                {"tag": tag, "pname": pname},
            )

        print("  ✓ All relationships created")

    # ================================================================
    # Final stats
    # ================================================================
    node_count = await Neo4jClient.execute_query("MATCH (n) RETURN count(n) as count")
    rel_count = await Neo4jClient.execute_query("MATCH ()-[r]->() RETURN count(r) as count")

    print(f"\n🎉 Seed complete!")
    print(f"   Total nodes: {node_count[0]['count']}")
    print(f"   Total relationships: {rel_count[0]['count']}")

    await Neo4jClient.close()


if __name__ == "__main__":
    asyncio.run(seed_knowledge_graph())
